[package]
name = "pixelator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
num = "0.4.0"
indicatif = "0.17.1"
gif = "0.11.4"